#!/bin/bash
# Automatically updates and copies scripts in ./Scripts to /usr/local/bin

echo "Update all scripts? (y/n)"
read y

cd Scripts

for a in *; do
	if [ $y = "n" ]
	then
		echo "Update $a? (y/n)"
		read yy

		if [ $yy = "y" ]
		then
			chmod +x $a
			cp -r $a /usr/local/bin/
		fi
	else
		chmod +x $a
		cp -r $a /usr/local/bin/
	fi
done

echo "Complete!"