#!/bin/bash
# Updates mpv via brew
# Requires mpv to already be installed!

echo "Update mpv?"
read y

brew rm mpv && brew install --HEAD --with-bundle --with-bluray-support --with-libdvdread --with-libquvi --with-little-cms2 --with-lua mpv

brew linkapps mpv