#!/bin/bash
action=$1
what=$2
echo "Attach or Detach? (A/D):"
echo $1
echo "- Mouse/Keyboard/Wacom Tablet (M/K/W)"
echo $2

actionT=""

if [ $action = "-a" ]
then
	actionT="attach-device"
else
	actionT="detach-device"
fi

thing=""

if [ $what = "-m" ]
then            
        thing="/usr/local/etc/logitechmouse.xml"
else    
	thing="/usr/local/etc/wacomtablet.xml"
fi      

echo "$actionT $thing"

sudo virsh $actionT Windows $thing
